create_tables.pl  --format="$SOURCE_FORMAT" --quote='"' --headerrows=$HEADER_ROWS --encoding=utf8 --ext=$TABLEEXT  --spec "$SPECDIR" --columndelimiter="$COLUMN_DELIMITER" --rowdelimiter='\r\n' --dir "$tabledir" --table "CI_BORR" --table CI_ACCOUNT --table CI_ACCOUNT_CARD --table "CI_BORR_PHONE" --table "CI_BORR_CARD" --table "CI_BORR_ADDR" --table "CI_BORR_MESSAGE" --table CI_COUNTRY --table CI_BORR_CAT --table CI_BORR_EMAIL --table CI_DEBT --table CI_DEBT_PAYMENT  --table CI_BORR_EVENT --table SY_CI_PARAM --table SY_CI_EVENT_TYPE --table SY_ALERT_TYPE | eval $MYSQL_LOAD

eval $MYSQL_LOAD <<EOF 
CREATE INDEX Borrowers_Id ON CI_BORR(CI_BORR_ID);
CREATE INDEX Borrower_Account_ID ON CI_ACCOUNT(CI_BORR_ID);
CREATE INDEX Borrower_Account_CAT_ID ON CI_ACCOUNT(CI_BORR_CAT_ID);
CREATE INDEX Account_card_ID ON CI_ACCOUNT_CARD(CI_BORR_CARD_ID);
CREATE INDEX Account_card_borr_ID ON CI_ACCOUNT_CARD(CI_BORR_ID);
CREATE INDEX Borrower_phone_id on CI_BORR_PHONE(CI_BORR_ID);
CREATE INDEX Borrower_Card_Id on CI_BORR_CARD(CI_BORR_ID);
CREATE INDEX Borrower_Borr_Card_Id on CI_BORR_CARD(CI_BORR_CARD_ID);
CREATE INDEX Borrrower_Addr_Id on CI_BORR_ADDR(CI_BORR_ID);
CREATE INDEX Borrower_Message_Id ON CI_BORR_MESSAGE(CI_BORR_ID);
CREATE INDEX Borrower_Cat_id ON CI_BORR_CAT(CI_BORR_CAT_ID);
CREATE INDEX Borrower_Email_ID ON CI_BORR_EMAIL(CI_BORR_ID);
CREATE INDEX Borrower_Debt_ID ON CI_DEBT(CI_BORR_ID);
CREATE INDEX Borrower_Debt_Payment_ID ON CI_DEBT_PAYMENT(CI_BORR_ID);
CREATE INDEX Account_Borrower_id ON CI_ACCOUNT(CI_BORR_ID);
CREATE INDEX Account_Borrower_cat_id ON CI_ACCOUNT(CI_BORR_CAT_ID);
CREATE INDEX SY_CI_PARAM_ID ON SY_CI_PARAM(SY_CI_PARAM_ID);
CREATE INDEX SY_CI_EVENT_TYPE_ID ON SY_CI_EVENT_TYPE(SY_CI_EVENT_TYPE_ID);
CREATE INDEX CI_BORR_EVENT_UNIT_ID ON CI_BORR_EVENT(CI_UNIT_ID);
CREATE INDEX CI_BORR_EVENT_CATALOG_ID ON CI_BORR_EVENT(CA_CATALOG_ID);
CREATE INDEX CI_BORR_EVENT_BORR_ID ON CI_BORR_EVENT(CI_BORR_ID);
CREATE INDEX CI_LOAN_ID ON CI_BORR_EVENT(CI_LOAN_ID);
CREATE INDEX SY_ALERT_TYPE_ID ON SY_ALERT_TYPE(SY_ALERT_TYPE_ID);
CREATE INDEX CI_COUNTRY_ID ON CI_COUNTRY(CI_COUNTRY_ID);
EOF
