create_tables.pl --format="$SOURCE_FORMAT" --yearoffsethack=50  "${TABLE_PARAMS[@]}" --table "CI_LOAN" --table "CA_BOOKING" --table CI_LOAN_RETURN_LOG  --table "CI_REM" --table "CI_REM_MSG" --table "CI_REM_MSG_STATUS" --table SY_DEBT_TYPE --table SY_PAYMENT_TYPE --table CI_RENEWAL | eval $MYSQL_LOAD

# Now copy the BarCodes table so we can have one for items and one for borrowers
$MYSQL <<EOF
CREATE INDEX CI_LOAN_CA_COPY_ID ON CI_LOAN(CA_COPY_ID);
CREATE INDEX CI_LOAN_CA_BOOKING_ID ON CI_LOAN(CA_BOOKING_ID);
CREATE INDEX CI_LOAN_CI_BORR_ID ON CI_LOAN(CI_BORR_ID);
CREATE INDEX CI_LOAN_GE_ORG_ID ON CI_LOAN(GE_ORG_ID);
CREATE INDEX CI_LOAN_CI_BORR_CARD_ID ON CI_LOAN(CI_BORR_CARD_ID);
CREATE INDEX CA_BOOKING_CI_BORR_ID ON CA_BOOKING(CI_BORR_ID);
CREATE INDEX CA_BOOKING_CA_BOOKING_ID ON CA_BOOKING(CA_BOOKING_ID);
CREATE INDEX CA_BOOKING_CA_COPY_ID ON CA_BOOKING(CA_COPY_ID);
CREATE INDEX CI_LOAN_RETURN_LOG_ID ON CI_LOAN_RETURN_LOG(CI_LOAN_RETURN_LOG_ID);
CREATE INDEX CI_LOAN_RETURN_LOG_BORR_ID ON CI_LOAN_RETURN_LOG(CI_BORR_ID);
CREATE INDEX CI_LOAN_RETURN_LOG_COPY_ID ON CI_LOAN_RETURN_LOG(CA_COPY_ID);
CREATE INDEX CI_REM_MSG_TYPE_ID ON CI_REM(SY_GE_MSG_TYPE_ID);
CREATE INDEX CI_REM_LOAN_ID ON CI_REM(CI_LOAN_ID);
CREATE INDEX CI_REM_REM_MSG_ID ON CI_REM(CI_REM_MSG_ID);
CREATE INDEX CI_REM_MSG_ID ON CI_REM_MSG(CI_REM_MSG_ID);
CREATE INDEX CI_REM_MSG_STATUS_ID ON CI_REM_MSG(CI_REM_MSG_STATUS_ID);
CREATE INDEX CI_REM_MSG_STATUS_ID2 ON CI_REM_MSG_STATUS(CI_REM_MSG_STATUS_ID);
CREATE INDEX SY_DEBT_TYPE_ID ON SY_DEBT_TYPE(SY_DEBT_TYPE_ID);
CREATE INDEX SY_PAYMENT_TYPE_ID ON SY_PAYMENT_TYPE(SY_PAYMENT_TYPE_ID);
CREATE INDEX IL_LOAN_COPY_ID ON IL_LOAN(CA_COPY_ID);
CREATE INDEX IL_LOAN_CATALOG_ID ON IL_LOAN(CA_CATALOG_ID);
CREATE INDEX IL_LIBRARY_ID ON IL_LIBRARY(IL_LIBRARY_ID);
CREATE INDEX IL_LIBRARY_GE_LIBRARY_ID ON IL_LIBRARY(GE_LIBRARY_ID);
CREATE INDEX CI_RENEWAL_LOAN_ID ON CI_RENEWAL(CI_LOAN_ID);
CREATE INDEX CI_RENEWAL_ID ON CI_RENEWAL(CI_RENEWAL_ID);
EOF
