create_tables.pl --format="$SOURCE_FORMAT" --quote='"' --headerrows=$HEADER_ROWS --encoding=utf8 --ext=$TABLEEXT --spec "$SPECDIR" --columndelimiter="$COLUMN_DELIMITER" --rowdelimiter='\r\n' --dir "$tabledir" --table "CI_LOAN" --table "CA_BOOKING" --table CI_LOAN_RETURN_LOG  --table "CI_REM" --table "CI_REM_MSG" --table "CI_REM_MSG_STATUS" | eval $MYSQL_LOAD
# Now copy the BarCodes table so we can have one for items and one for borrowers
$MYSQL <<EOF
CREATE INDEX CI_LOAN_CA_COPY_ID ON CI_LOAN(CA_COPY_ID);
CREATE INDEX CI_LOAN_CA_BOOKING_ID ON CI_LOAN(CA_BOOKING_ID);
CREATE INDEX CI_LOAN_CI_BORR_ID ON CI_LOAN(CI_BORR_ID);
CREATE INDEX CI_LOAN_GE_ORG_ID ON CI_LOAN(GE_ORG_ID);
CREATE INDEX CI_LOAN_CI_BORR_CARD_ID ON CI_LOAN(CI_BORR_CARD_ID);
CREATE INDEX CA_BOOKING_CI_BORR_ID ON CA_BOOKING(CI_BORR_ID);
CREATE INDEX CA_BOOKING_CA_BOOKING_ID ON CA_BOOKING(CA_BOOKING_ID);
CREATE INDEX CA_BOOKING_CA_COPY_ID ON CA_BOOKING(CA_COPY_ID);
CREATE INDEX CI_LOAN_RETURN_LOG_ID ON CI_LOAN_RETURN_LOG(CI_LOAN_RETURN_LOG_ID);
CREATE INDEX CI_LOAN_RETURN_LOG_BORR_ID ON CI_LOAN_RETURN_LOG(CI_BORR_ID);
CREATE INDEX CI_LOAN_RETURN_LOG_COPY_ID ON CI_LOAN_RETURN_LOG(CA_COPY_ID);
CREATE INDEX CI_REM_MSG_TYPE_ID ON CI_REM(SY_GE_MSG_TYPE_ID);
CREATE INDEX CI_REM_LOAN_ID ON CI_REM(CI_LOAN_ID);
CREATE INDEX CI_REM_REM_MSG_ID ON CI_REM(CI_REM_MSG_ID);
CREATE INDEX CI_REM_MSG_ID ON CI_REM_MSG(CI_REM_MSG_ID);
CREATE INDEX CI_REM_MSG_STATUS_ID ON CI_REM_MSG(CI_REM_MSG_STATUS_ID);
CREATE INDEX CI_REM_MSG_STATUS_ID2 On CI_REM_MSG_STATUS(CI_REM_MSG_STATUS_ID);
EOF
