
create_tables.pl "${TABLE_PARAMS[@]}"  --table PE_CIRC_RULE --table PE_FREQ_RULE --table PE_FREQ_TYPE --table PE_FREQ_VALUE --table PE_HANDLE_TYPE --table PE_PERIOD --table PE_RELEASE --table PE_REL_PATTERN --table PE_SUBSCRIPTION --table PE_SUBSCR_ARR --table PE_SUBSCR_REMINDER --table PE_SUBSCR_STORAGE_INFO --table PE_TITLE --table PE_TYPE_OF_PE_1 --table PE_TYPE_OF_PE_2 | eval $MYSQL_LOAD

$MYSQL <<EOF
CREATE INDEX PE_FREQ_RULE_TYPE_ID ON PE_FREQ_RULE(PE_FREQ_TYPE_ID);
CREATE INDEX PE_FREQ_RULE_TITLE_ID ON PE_FREQ_RULE(PE_TITLE_ID);
CREATE INDEX PE_FREQ_RULE_FREQ_RULE ON PE_FREQ_RULE(FREQ_RULE);
CREATE INDEX PE_FREQ_TYPE_ID ON PE_FREQ_TYPE(PE_FREQ_TYPE_ID);
CREATE INDEX PE_FREQ_TYPE_LA_KEY_ID ON PE_FREQ_TYPE(LA_KEY_ID);
CREATE INDEX PE_FREQ_TYPE_DESCR ON PE_FREQ_TYPE(DESCR);
CREATE INDEX PE_HANDLE_TYPE_ID ON PE_HANDLE_TYPE(PE_HANDLE_TYPE_ID);
CREATE INDEX PE_PERIOD_ID ON PE_PERIOD(PE_PERIOD_ID);
CREATE INDEX PE_PERIOD_TITLE_ID ON PE_PERIOD(PE_TITLE_ID);
CREATE INDEX PE_PERIOD_CATALOG_ID ON PE_PERIOD(CA_CATALOG_ID);
CREATE INDEX PE_RELEASE_ID ON PE_RELEASE(PE_RELEASE_ID);
CREATE INDEX PE_RELEASE_PERIOD_ID ON PE_RELEASE(PE_PERIOD_ID);
CREATE INDEX PE_REL_PATTERN_TITLE_ID ON PE_REL_PATTERN(PE_TITLE_ID);
CREATE INDEX PE_SUBSCRIPTION_ID ON PE_SUBSCRIPTION (PE_SUBSCRIPTION_ID);
CREATE INDEX PE_SUBSCR_ARR_RELEASE_ID ON PE_SUBSCR_ARR(PE_RELEASE_ID);
CREATE INDEX PE_SUBSCR_ARR_SUBSCRIPTION_ID ON PE_SUBSCR_ARR(PE_SUBSCRIPTION_ID);
CREATE INDEX PE_SUBSCR_ARR_COPY_ID ON PE_SUBSCR_ARR(CA_COPY_ID);
CREATE INDEX PE_SUBSCR_REMINDER_ID ON PE_SUBSCR_REMINDER(PE_SUBSCR_REMINDER_ID);
CREATE INDEX PE_SUBSCR_REMINDER_RELEASE_ID ON PE_SUBSCR_REMINDER(PE_RELEASE_ID);
CREATE INDEX PE_SUBSCR_REMINDER_SUBSCRIPTION_ID ON PE_SUBSCR_REMINDER(PE_SUBSCRIPTION_ID);
CREATE INDEX PE_SUBSCR_STORAGE_INFO_ID ON PE_SUBSCR_STORAGE_INFO(PE_SUBSCR_STORAGE_INFO_ID);
CREATE INDEX PE_SUBSCR_STORAGE_INFO_SUBSCRIPTION_ID ON PE_SUBSCR_STORAGE_INFO(PE_SUBSCRIPTION_ID);
CREATE INDEX PE_TITLE_ID ON PE_TITLE(PE_TITLE_ID);
CREATE INDEX PE_TITLE_CATALOG_ID ON PE_TITLE(CA_CATALOG_ID);
CREATE INDEX PE_FREQ_RULE_ID ON PE_FREQ_RULE(FREQ_RULE);
CREATE INDEX PE_FREQ_RULE_FREQ_TYPE_ID ON PE_FREQ_RULE(PE_FREQ_TYPE_ID);
CREATE INDEX PE_FREQ_VALUE_ID ON PE_FREQ_VALUE(PE_FREQ_VALUE_ID);
CREATE INDEX PE_FREQ_VALUE_VALUE ON PE_FREQ_VALUE(VALUE);
CREATE INDEX PE_FREQ_VALUE_LA_KEY ON PE_FREQ_VALUE(LA_KEY_ID);
CREATE INDEX PE_FREQ_VALUE_FREQ_TYPE_ID ON PE_FREQ_VALUE(PE_FREQ_TYPE_ID);
EOF


