
create_tables.pl  --format="$SOURCE_FORMAT" --quote='"' --headerrows=$HEADER_ROWS --encoding=utf8 --ext=$TABLEEXT  --spec "$SPECDIR" --columndelimiter="$COLUMN_DELIMITER" --rowdelimiter='\r\n' --dir "$tabledir" --table "CI_BORR" --table CI_ACCOUNT --table CI_ACCOUNT_CARD --table "CI_BORR_PHONE" --table "CI_BORR_CARD" --table "CI_BORR_ADDR" --table "CI_BORR_MESSAGE" --table CI_COUNTRY --table CI_BORR_CAT --table CI_BORR_EMAIL --table CI_DEBT --table CI_DEBT_PAYMENT --table CI_BORR_EVENT --table SY_CI_PARAM --table SY_CI_EVENT_TYPE --table SY_ALERT_TYPE --table SY_SEX --table SY_USER --table CI_REM --table CI_REM_MSG --table CI_REM_MSG_STATUS --table CI_REM_MSG_OCCATION | eval $MYSQL_LOAD

create_tables.pl  --format="$SOURCE_FORMAT" --quote='"' --headerrows=$HEADER_ROWS --encoding=utf8 --ext=$TABLEEXT  --spec "$SPECDIR" --columndelimiter="$COLUMN_DELIMITER" --rowdelimiter='\r\n' --dir "$tabledir" --table "GE_ADDR" --table "GE_AUTO_UPDATE_TYPE" --table "GE_CURRENCY" --table "GE_LIBRARY" --table "GE_MSG_LANGUAGE" --table "GE_ORDER_LANGUAGE" --table "GE_ORG" --table "GE_PREMISES"  --table "GE_SEND_OCCATION"  --table "SY_GE_MSG_TYPE" --table "SY_GE_MSG_FORM" --table "SY_GE_FORMAT"| eval $MYSQL_LOAD

eval $MYSQL_LOAD <<EOF 
CREATE INDEX Borrowers_Id ON CI_BORR(CI_BORR_ID);
CREATE INDEX Borrower_Account_ID ON CI_ACCOUNT(CI_BORR_ID);
CREATE INDEX Borrower_Account_CAT_ID ON CI_ACCOUNT(CI_BORR_CAT_ID);
CREATE INDEX Account_card_ID ON CI_ACCOUNT_CARD(CI_BORR_CARD_ID);
CREATE INDEX Account_card_borr_ID ON CI_ACCOUNT_CARD(CI_BORR_ID);
CREATE INDEX Borrower_phone_id on CI_BORR_PHONE(CI_BORR_ID);
CREATE INDEX Borrower_Card_Id on CI_BORR_CARD(CI_BORR_ID);
CREATE INDEX Borrower_Borr_Card_Id on CI_BORR_CARD(CI_BORR_CARD_ID);
CREATE INDEX Borrrower_Addr_Id on CI_BORR_ADDR(CI_BORR_ID);
CREATE INDEX Borrower_Message_Id ON CI_BORR_MESSAGE(CI_BORR_ID);
CREATE INDEX Borrower_Cat_id ON CI_BORR_CAT(CI_BORR_CAT_ID);
CREATE INDEX Borrower_Email_ID ON CI_BORR_EMAIL(CI_BORR_ID);
CREATE INDEX Borrower_Debt_ID ON CI_DEBT(CI_BORR_ID);
CREATE INDEX Borrower_Debt_Payment_ID ON CI_DEBT_PAYMENT(CI_BORR_ID);
CREATE INDEX Account_Borrower_id ON CI_ACCOUNT(CI_BORR_ID);
CREATE INDEX Account_Borrower_cat_id ON CI_ACCOUNT(CI_BORR_CAT_ID);
CREATE INDEX SY_CI_PARAM_ID ON SY_CI_PARAM(SY_CI_PARAM_ID);
CREATE INDEX SY_CI_EVENT_TYPE_ID ON SY_CI_EVENT_TYPE(SY_CI_EVENT_TYPE_ID);
CREATE INDEX CI_BORR_EVENT_UNIT_ID ON CI_BORR_EVENT(CI_UNIT_ID);
CREATE INDEX CI_BORR_EVENT_CATALOG_ID ON CI_BORR_EVENT(CA_CATALOG_ID);
CREATE INDEX CI_BORR_EVENT_BORR_ID ON CI_BORR_EVENT(CI_BORR_ID);
CREATE INDEX CI_LOAN_ID ON CI_BORR_EVENT(CI_LOAN_ID);
CREATE INDEX SY_ALERT_TYPE_ID ON SY_ALERT_TYPE(SY_ALERT_TYPE_ID);
CREATE INDEX CI_COUNTRY_ID ON CI_COUNTRY(CI_COUNTRY_ID);
CREATE UNIQUE INDEX SY_SEX_ID ON SY_SEX(SY_SEX_ID);
CREATE UNIQUE INDEX SY_GEM_MSG_TYPE_ID ON SY_GE_MSG_TYPE(SY_GE_MSG_TYPE_ID);
CREATE INDEX SY_GEM_MSG_TYPE_AREA_ID ON SY_GE_MSG_TYPE(SY_GE_MSG_AREA_ID);
CREATE INDEX SY_GEM_MSG_TYPE_LA_KEY_ID ON SY_GE_MSG_TYPE(LA_KEY_ID);
CREATE INDEX SY_USER_SY_USER_ID ON SY_USER(SY_USER_ID);
CREATE INDEX CI_REM_ID ON CI_REM(SY_GE_MSG_TYPE_ID);
CREATE INDEX CI_REM_CI_LOAN_ID ON CI_REM(CI_LOAN_ID);
CREATE INDEX CI_REM_CI_REM_MSG_ID ON CI_REM(CI_REM_MSG_ID);
CREATE INDEX CI_REM_SY_ALERT_TYPE_ID ON CI_REM(SY_ALERT_TYPE_ID);
CREATE INDEX CI_REM_MSG_CI_REM_MSG_ID ON CI_REM_MSG(CI_REM_MSG_ID);
CREATE INDEX CI_REM_MSG_SY_USER_ID_CREATE ON CI_REM_MSG(SY_USER_ID_CREATE);
CREATE INDEX CI_REM_MSG_CI_REM_MSG_STATUS_ID ON CI_REM_MSG(CI_REM_MSG_STATUS_ID);
CREATE INDEX GE_ADDR_GE_ADDR_ID ON GE_ADDR(GE_ADDR_ID);
CREATE INDEX GE_ADDR_GE_ORG_ID ON GE_ADDR(GE_ORG_ID);
CREATE INDEX GE_AUTO_UPDATE_TYPE_GE_AUTO_UPDATE_TYPE_ID ON GE_AUTO_UPDATE_TYPE(GE_AUTO_UPDATE_TYPE_ID);
CREATE INDEX GE_AUTO_UPDATE_TYPE_CODE ON GE_AUTO_UPDATE_TYPE(CODE);

EOF
