SELECT level1.`SEQUENCE` AS serialseq_x, level2.`SEQUENCE` AS serialseq_y, level3.`SEQUENCE` AS serialseq_z FROM
  (SELECT * FROM PE_REL_PATTERN WHERE RULE_LEVEL=1) AS level1
  LEFT OUTER JOIN (SELECT * FROM PE_REL_PATTERN WHERE RULE_LEVEL=2) AS level2 USING(PE_TITLE_ID)
  LEFT OUTER JOIN (SELECT * FROM PE_REL_PATTERN WHERE RULE_LEVEL=3) AS level3 USING(PE_TITLE_ID)
WHERE PE_TITLE_ID = ?;
