SELECT t1.CA_MEDIA_TYPE_ID, t0.DESCR FROM CA_MEDIA_TYPE AS t0 join CA_MEDIA_TYPE AS t1 ON t0.CA_MEDIA_TYPE_ID=t1.CA_MEDIA_TYPE_ID_PARENT
UNION
SELECT CA_MEDIA_TYPE_ID, DESCR FROM CA_MEDIA_TYPE WHERE CA_MEDIA_TYPE_ID_PARENT IS NULL;
