SELECT 'MV' AS IdBranchCode,
       `Systemnr(Patron)` AS IdBorrower,
        `LÅNT.NR` AS BarCode,
        `ANM` AS Comment,
        `Föd.datum` AS BirthDate,
        `Skapad(Patron)` AS RegDate,
        `Uppdaterad(Patron)` AS UpdatedDate,
        `Lånt.typ` AS IdBorrowerCategory,
        `NAMN` AS FullName,
	IF(`Valt språk` = 'swe', 'sv-SE', IF(`Valt språk` = 'eng', 'en', NULL)) as `lang`,
	`Tot utlån` AS `BorrowerAttribute:TOT_LAN`,
	`Tot förny` AS `BorrowerAttribute:TOT_OMLAN`,
	`Nuv utlån` AS `BorrowerAttribute:ÖVRIGT`,
	`Skuld` AS `BorrowerAttribute:ÖVRIGT`,
	`Cirk.aktiv` AS `BorrowerAttribute:ÖVRIGT`,
	`Valt språk` AS `BorrowerAttribute:LANG`,
	`Kravmetod` AS `BorrowerAttribute:NOTICE_PRE`,
        `Systemnr(Patron)` AS  `BorrowerAttribute:SIERRA_ID`,
	`Skapad(Patron)` AS `BorrowerAttribute:ÖVRIGT`,
	`Uppdaterad(Patron)` AS `BorrowerAttribute:ÖVRIGT`,
	`Ant revid.(Patron)` AS `BorrowerAttribute:ÖVRIGT`,
	`PERSONNUMMER` AS `BorrowerAttribute:ÖVRIGT`,
	`ANM` AS `BorrowerAttribute:ÖVRIGT`
FROM Patrons
