
package CommonMarcMappings;
    
$VERSION     = 1.00;
@ISA         = qw(Exporter);
@EXPORT      = qw(%common_marc_mappings);
@EXPORT_OK   = qw();

our %common_marc_mappings = (
    'isbn'                             => { map => { '020' => 'a' } },
    'issn'                             => { map => { '022' => 'a' } },
    'catid'                            => { map => { '035' => 'a' } },
    'klassifikationskod'               => { map => { '084' => 'a' } },
    'klassifikationsdel_av_uppställningssignum' => { map => { '852' => 'h' } },
    'uppställningsord'                 => { map => { '852' => 'l' } },
    'titel'                            => { map => { '245' => 'a' } },
    'allmän_medieterm'                 => { map => { '245' => 'h' } },
    'beståndsuppgift'                  => { map => { '866' => 'a' } },
    'anmärkning_allmän'                => { map => { '500' => 'a' } },
    'publish_no'                       => { map => { '596' => 'l' } },
    'intern_anmärkning_av_systemteknisk_karaktär' => { map => { '599' => 'a' } },
    'ämnesord'                         => { map => { '650' => 'a' } },
    'okontrollerad_term'               => { map => { '653' => 'a' } },
    'fysisk_beskrivning'               => { map => { '300' => 'e' } },
    'genre_form_uppgift_eller_fokusterm' => { map => { '655' => 'a' } },
    'homebranch'                       => { itemcol => 'homebranch', map => { '952' => 'a' } },
    'holdingbranch'                    => { itemcol => 'holdingbranch', map => { '952' => 'b' } },
    'localshelf'                       => { itemcol => 'location', map => { '952' => 'c' } },
    'date_acquired'                    => { itemcol => 'dateaccessioned', map => { '952' => 'd' } },
    'price'                            => { numeric => 1, itemcol => ['price', 'replacementprice'],  map => { '952' => [ 'g', 'v' ] } },
    'total_number_of_checkouts'        => { numeric => 1, itemcol => 'issues', map => { '952' => 'l' } },
    'total_number_of_renewals'         => { numeric => 1, itemcol => 'renewals', map => { '952' => 'm' } },
    'call_number'                      => { itemcol => 'itemcallnumber', map => { '952' => 'o' } },
    'barcode'                          => { itemcol => 'barcode', map => { '952' => 'p' } },
    'date_last_seen'                   => { itemcol => 'datelastseen', map => { '952' => 'r' } },
    'date_last_checkout'               => { itemcol => 'datelastborrowed', map => { '952' => 's' } },
    'internal_staff_note'              => { itemcol => 'itemnotes_nonpublic', map => { '952' => 'x' } },
    'itemtype'                         => { itemcol => 'itype', map => { '952' => 'y' } },
    'lost_status'                      => { itemcol => 'itemlost', map => { '952' => '1' } },
    'damaged_status'                   => { itemcol => 'damaged', map => { '952' => '4' } },
    'not_for_loan'                     => { itemcol => 'notforloan', map => { '952' => '7' } },
    'collection_code'                  => { itemcol => 'ccode', map => { '952' => '8' } },
    'subjects'                         => { map => { '653' => 'b' } },
    'libra_subjects'                   => { map => { '976' => 'b' } },
    'biblioitemtype'                   => { map => { '942' => 'c' }, append => 0 },

    'items.barcode'                    => { itemcol => 'barcode', map => { '952' => 'p' }},
    'items.booksellerid'               => { itemcol => 'booksellerid', map => { '952' => 'e' }},
    'items.ccode'                      => { itemcol => 'ccode', map => { '952' => '8' }},
    'items.cn_sort'                    => { itemcol => 'cn_sort', map => { '952' => '6' }},
    'items.cn_source'                  => { itemcol => 'cn_source', map => { '952' => '2' }},
    'items.coded_location_qualifier'   => { itemcol => 'coded_location_qualifier', map => { '952' => 'f' }},
    'items.copynumber'                 => { numeric => 1, itemcol => 'copynumber', map => { '952' => 't' }},
    'items.damaged'                    => { numeric => 1, itemcol => 'damaged', map => { '952' => '4' }},
    'items.dateaccessioned'            => { itemcol => 'dateaccessioned', map => { '952' => 'd' }},
    'items.datelastborrowed'           => { itemcol => 'datelastborrowed', map => { '952' => 's' }},
    'items.datelastseen'               => { itemcol => 'datelastseen', map => { '952' => 'r' }},
    'items.enumchron'                  => { itemcol => 'enumchron', map => { '952' => 'h' }},
    'items.holdingbranch'              => { itemcol => 'holdingbranch', map => { '952' => 'b' }},
    'items.homebranch'                 => { itemcol => 'homebranch', map => { '952' => 'a' }},
    'items.issues'                     => { numeric => 1, itemcol => 'issues', map => { '952' => 'l' }},
    'items.itemcallnumber'             => { itemcol => 'itemcallnumber', map => { '952' => 'o' }},
    'items.itemlost'                   => { numeric => 1, itemcol => 'itemlost', map => { '952' => '1' }},
    'items.itemnotes'                  => { itemcol => 'itemnotes', map => { '952' => 'z' }},
    'items.itemnotes_nonpublic'        => { itemcol => 'itemnotes_nonpublic', map => { '952' => 'x' }},
    'items.itemnumber'                 => { numeric => 1, itemcol => 'itemnumber', map => { '952' => '9' }},
    'items.itype'                      => { itemcol => 'itype', map => { '952' => 'y' }},
    'items.location'                   => { itemcol => 'location', map => { '952' => 'c' }},
    'items.materials'                  => { numeric => 1, itemcol => 'materials', map => { '952' => '3' }},
    'items.notforloan'                 => { itemcol => 'notforloan', map => { '952' => '7' }},
    'items.onloan'                     => { itemcol => 'onloan', map => { '952' => 'q' }},
    'items.price'                      => { numeric => 1, itemcol => 'price', map => { '952' => 'g' }},
    'items.renewals'                   => { numeric => 1, itemcol => 'renewals', map => { '952' => 'm' }},
    'items.replacementprice'           => { numeric => 1, itemcol => 'replacementprice', map => { '952' => 'v' }},
    'items.replacementpricedate'       => { numeric => 1, itemcol => 'replacementpricedate', map => { '952' => 'w' }},
    'items.reserves'                   => { numeric => 1, itemcol => 'reserves', map => { '952' => 'n' }},
    'items.restricted'                 => { numeric => 1, itemcol => 'restricted', map => { '952' => '5' }},
    'items.stack'                      => { itemcol => 'stack', map => { '952' => 'j' }},
    'items.stocknumber'                => { numeric => 1, itemcol => 'stocknumber', map => { '952' => 'i' }},
    'items.uri'                        => { itemcol => 'uri', map => { '952' => 'u' }},
    'items.withdrawn'                  => { numeric => 1, itemcol => 'withdrawn', map => { '952' => '0' }},
    
    'sierra_barcode'                   => { map => { '945' => 'i' } },
    'sierra_created'                   => { map => { '945' => 'z' } },
    'sierra_total_checkouts'           => { map => { '945' => 'u' } },
    'sierra_total_renewals'            => { map => { '945' => 'v' } },
    'sierra_price'                     => { map => { '945' => 'p' } },
    'sierra_note'                      => { map => { '945' => 'n' } },
    'sierra_message'                   => { map => { '945' => 'm' } },
    'sierra_copy_number'               => { map => { '945' => 'g' } },
    'sierra_call_number'               => { map => { '945' => 'a' } },
    'sierra_volume'                    => { map => { '945' => 'c' } },
    'sierra_location'                  => { map => { '945' => 'l' } },
    'sierra_sysid'                     => { map => { '945' => 'i' } },
    'sierra_restricted'                => { map => { '945' => 'r' } },
    'sierra_status'                    => { map => { '945' => 's' } },
    'sierra_itemtype'                  => { map => { '945' => 't' } },
    'sierra_sysnumber'                 => { map => { '945' => 'y' } },
    'sierra_bib_sysnumber'             => { map => { '907' => 'a' } },
    
    );

1;
